version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: html-proofer
    versions:
    - 3.18.5
    - 3.18.6
    - 3.18.8
    - 3.19.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: uswds-jekyll
    versions:
    - 5.3.0
