title: Join the Technology Transformation Services
description: The Technology Transformation Service’s (TTS) mission is to lead the digital transformation of the federal government by helping agencies build, buy, and share technology that allows them to provide more accessible, efficient, and effective products and services to the American people.

theme: uswds-jekyll

plugins:
  - jekyll-redirect-from

site_width: wide

# GitHub information
# This is used for adding an edit this page link to the footer
github:
  organization: 18F
  repository: join.tts.gsa.gov
  default_branch: master

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-48605964-32

exclude:
  - CONTRIBUTING.md
  - _config.yml
  - .travis.yml
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - vendor
  - manifest.yml
  - node_modules
  - .nvmrc
  - .sass-cache
  - todo.txt

# Configuration for DAP, add your agency ID here:
dap_agency: GSA
dap_subagency: TTS

# Uncomment to enable AnchorJS functionality on docs layout.
# See https://github.com/bryanbraun/anchorjs for more information.
# anchor_js_targets: [h1, h2, h3, h4, h5, h6]

# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.

# search_site_handle: searchgov-site-handle

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      sidenav: primary
  - scope:
      path: pages/positions
      type: pages
    values:
      layout: job
  - scope:
      path: pages/performance-profiles
      type: pages
    values:
      layout: job

styles:
  - /assets/css/index.css
  
# Site Navigation
primary_navigation:
  - name: Home
    url: /
  - name: Blog
    url: /blog/
  - name: Document
    url: /document/
  - name: Document with sidenav
    url: /document-with-sidenav/
  - name: Document submenu
    children:
      - name: Navigation link
        url: "#main-content"
      - name: Navigation link
        url: "#main-content"
      - name: Navigation link
        url: "#main-content"

secondary_navigation:
  - name: Secondary link
    url: "#main-content"
  - name: Another secondary link
    url: "#main-content"