title: Join the Technology Transformation Services

theme: uswds-jekyll

site_width: wide

# GitHub information
# This is used for adding an edit this page link to the footer
github:
  organization: 18F
  repository: join.tts.gsa.gov
  default_branch: master

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-48605964-32

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor
- gulpfile.js
- manifest.yml
- package.json
- Staticfile
- Staticfile.auth
- node_modules
- .nvmrc
- .sass-cache
- todo.txt

# Configuration for DAP, add your agency ID here:
# dap_agency: GSA

# Uncomment to enable AnchorJS functionality on docs layout.
# See https://github.com/bryanbraun/anchorjs for more information.
# anchor_js_targets: [h1, h2, h3, h4, h5, h6]

# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.

# search_site_handle: searchgov-site-handle

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: custom
      sidenav: primary

styles:
  - /assets/css/site.css
