# OpenGraph / Twitter metadata
title: Join the Technology Transformation Services
small_title: Join TTS
smallest_title: Join TTS
description: The Technology Transformation Service’s (TTS) mission is to lead the digital transformation of the federal government by helping agencies build, buy, and share technology that allows them to provide more accessible, efficient, and effective products and services to the American people.
name: Join the Technology Transformation Services

# GA and GitHub data

repo: https://github.com/18F/join.tts.gsa.gov
org_name: 18f
repo_name: join.tts.gsa.gov
uswds_path: assets/vendor/uswds

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor
- gulpfile.js
- manifest.yml
- package.json
- Staticfile
- Staticfile.auth
- node_modules
- .nvmrc
- .sass-cache
- todo.txt
- assets/sass


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    #permalink: /:path/
