version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v2-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v2-{{ arch }}-{{ .Branch }}
            - gem-cache-v2
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-v2-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Build the site
          command: bundle exec jekyll build
      - run:
          name: Check for broken links
          command: bundle exec rake test
