name: archive closed jobs

on:
  push:
    branches:
      - asdfasdfksjagdlhasdghasdflkj

jobs:
  archive:
    name: archive closed jobs
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: build the site
        run: bundle exec jekyll build
      - uses: actions/github-script@v6
        id: archive
        with:
          script: |
            const fs = require("fs/promises");
            const path = require("path");

            const jobs = JSON.parse(await fs.readFile("_site/jobs.json"));
            const closed = jobs.filter(({ status }) => status === "closed");

            for await (const job of closed) {
              const pathname = new URL(job.url).pathname;
              const renderedPath = path.join("_site", pathname);
              const archivePath = path.join("archive", path.basename(pathname));

              await fs.rename(renderedPath, archivePath);

              const indexPath = path.join(archivePath, "index.html");
              const content = await fs.readFile(indexPath, { encoding: "utf-8" });
              const frontmatter = `---\ntitle: ${job.title}\norg: ${job.org}\nlayout: raw\n---\n`;
              await fs.writeFile(indexPath, `${frontmatter}${content}`, {
                encoding: "utf-8",
              });

              await fs.rm(path.join("positions", job.name));
            }

            if(closed.length > 0) {
              core.setOutput("archived", "true");
            }

      - if: steps.archive.outputs.archived == 'true'
        name: commit the changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "tts@gsa.gov"
          git config --global user.name "TTSJobs Automatic Archiver"
          export BRANCH="archiver/$(date +"%s")"
          git checkout -b $BRANCH
          git add archive/ positions/
          git commit -m "archiving closed jobs"
          git push -u origin $BRANCH
          gh pr create --base main --title "Archive closed jobs" --body "This pull request was created automatically. It is archiving job postings that are now closed."
          gh pr merge $BRANCH --auto --merge
