name: invalid links check

on: [pull_request]

jobs:
  root-relative-links-pages:
    name: no root-relative links in pages
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v3
      - name: check that root-relative internal links are prefixed (pages)
        uses: mgwalker/action-no-root-relative-links@v1
        with:
          path: pages
          message: Internal link begins with /, but should begin with {{ site.baseurl }}/ or use {% link %}

  root-relative-links-postings:
    name: no root-relative links in job postings
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v3
      - name: check that root-relative internal links are prefixed (pages)
        uses: mgwalker/action-no-root-relative-links@v1
        with:
          path: positions
          message: Internal link begins with /, but should begin with {{ site.baseurl }}/ or use {% link %}

  internal-links:
    name: verify internal links are valid
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: build the site
        run: bundle exec jekyll build
      - name: check for broken links
        uses: mgwalker/action-htmlproofer@v1
        with:
          path: _site
          args: --disable-external --allow-missing-href
